"""add_foreign_keys

Revision ID: df3c08f162d8
Revises: 3ef4f9cf8388
Create Date: 2026-02-14 18:48:54.028505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3c08f162d8'
down_revision: Union[str, Sequence[str], None] = '3ef4f9cf8388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'positions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'volume_tracking', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volume_tracking', type_='foreignkey')
    op.drop_constraint(None, 'user_preferences', type_='foreignkey')
    op.drop_constraint(None, 'user_api_keys', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'positions', type_='foreignkey')
    # ### end Alembic commands ###
